### PR TITLE
implements speedglm via a wrapper

### PR DESCRIPTION
**Pull request by nhejazi**
The purpose of this PR is to implement `speedglm::speedglm` over the current use of `stats::glm`, as discussed in #16. To that end, the substantive changes here include

* a new wrapper function `fast_glm`, which is called by the internal functions currently using `stats::glm`. `fast_glm` is implemented with `try...Catch` and contains a stack trace to identify functions where `speedglm` breaks (and `glm` is used instead).

* some alterations to the code base to follow nomenclature conventions similar to those used in the tidyverse -- as explained in the [tidyverse style guide](http://style.tidyverse.org/).

__Note:__ This PR is currently a placeholder and should only be merged once the actual speed increases afforded by use of `speedglm` are thoroughly benchmarked. As of this writing, it is unclear whether `speedglm` actually helps (see rudimentary benchmarking in #16 for details).

### CODE REVIEW

**Comment by benkeser** [comment]
Could you please try to benchmark for a larger data set (e.g., n = 1000 or n = 5000) for that same example? I suspect speed increases will be present for larger n. 

Also should be faster for many covariates (this was the situation I was really hoping to use it for), as in the example below. Could you please also benchmark this example?

```r
set.seed(1234)
n <- 1000
t_0 <- 6
trt <- rbinom(n, 1, 0.5)
# e.g., study site
adjustVars <- data.frame(site = (rbinom(n,1,0.5) + 1))
ftime <- round(1 + runif(n, 1, 350) - trt + adjustVars$site)
ftype <- round(runif(n, 0, 1))

#' make a formula that will implement an empirical hazard
#' estimator when called in estimateHazard
get.ftimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype>0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}


#' make a formula that will implement an empirical hazard
#' estimator when called in estimateCensoring
get.ctimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype==0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}

glm.ftime <- get.ftimeForm(trt = trt, site = adjustVars$site)
glm.ctime <- get.ctimeForm(trt = trt, site = adjustVars$site)

# now run survtmle with method = "hazard", glm.ftime = glm.ftime, glm.ctime = glm.ctime
```

**Comment by nhejazi** [comment]
Question about your example -- does the following error simply mean that `t_0` needs to be made smaller?
```
Error in checkInputs(ftime = ftime, ftype = ftype, trt = trt, t0 = t0, : No observed events by t0.
Traceback:

1. system.time(fit <- survtmle(ftime = ftime, ftype = ftype, trt = A, 
 .     adjustVars = W, glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime, 
 .     method = "hazard", t0 = t_0))
2. survtmle(ftime = ftime, ftype = ftype, trt = A, adjustVars = W, 
 .     glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime, 
 .     method = "hazard", t0 = t_0)
3. checkInputs(ftime = ftime, ftype = ftype, trt = trt, t0 = t0, 
 .     adjustVars = adjustVars, SL.ftime = SL.ftime, SL.ctime = SL.ctime, 
 .     SL.trt = SL.trt, glm.ftime = glm.ftime, glm.ctime = glm.ctime, 
 .     glm.trt = glm.trt, returnIC = returnIC, returnModels = returnModels, 
 .     ftypeOfInterest = ftypeOfInterest, trtOfInterest = trtOfInterest, 
 .     bounds = bounds, verbose = verbose, tol = tol, Gcomp = Gcomp, 
 .     method = method)
4. stop("No observed events by t0.")
```

**Comment by nhejazi** [comment]
Benchmarking using the initial example is now complete. See [here](https://www.stat.berkeley.edu/~nhejazi/misc/benchmark_glm.html) for a Jupyter notebook examining the performance of `survtmle` with `glm` on branch `master`, and [here](https://www.stat.berkeley.edu/~nhejazi/misc/benchmark_speedglm.html) for a notebook benchmarking with the `speedglm` implementation.

**Comment by nhejazi** [comment]
5ff51dc adds support for specifying the type of regression (linear vs. logistic; defaults to logistic) in the various `estimate*` and `fluctuate*` funs called by either `mean_tmle` or `hazard_tmle`. This new `glm.family` argument is then passed to the `fast_glm` wrapper function.

**Comment by nhejazi** [comment]
@benkeser -- benchmarks based on your new example are now nearing completetion; see below:

## branch `master`
### n = 100:
```
R > system.time(
...     fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,
...                     glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,
...                     method = "hazard", t0 = t_0)
... )
   user  system elapsed
  2.963   0.014   2.976
```

```
R > m4 <- microbenchmark(unit = "s",
...     fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,
...                     glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,
...                     method = "hazard", t0 = t_0)
... )
R > summary(m4)
                                                                                                                                                                                   expr
1 fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,      glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,      method = "hazard", t0 = t_0)
       min       lq    mean   median       uq      max neval
1 2.286276 2.295131 2.31904 2.299909 2.302539 3.938296   100
```

### n = 1000:
```
R > system.time(
...     fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,
...                     glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,
...                     method = "hazard", t0 = t_0)
... )
    user   system  elapsed
1416.898   13.858 1430.593
```

```
```

---

## branch `speedglm`
### n = 100:
```
❯ system.time(
...     fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,
...                     glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,
...                     method = "hazard", t0 = t_0)
... )
'speedglm' ran into an error in estimateCensoring ... using 'glm' instead.
'speedglm' ran into an error in estimateHazards ... using 'glm' instead.
   user  system elapsed
  2.535   0.185   2.743
```

```
❯ suppressMessages(
...     m4 <- microbenchmark(unit = "s",
...         fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,
...                         glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,
...                         method = "hazard", t0 = t_0)
...     )
... )


❯ summary(m4)
                                                                                                                                                                                   expr
1 fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,      glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,      method = "hazard", t0 = t_0)
      min       lq     mean median       uq      max neval
1 2.02714 2.212268 2.423665 2.4465 2.619865 3.134974   100
```

### n = 1000:
```
❯ system.time(
...     fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,
...                     glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,
...                     method = "hazard", t0 = t_0)
... )
'speedglm' ran into an error in estimateCensoring ... using 'glm' instead.
'speedglm' ran into an error in estimateHazards ... using 'glm' instead.
    user   system  elapsed
1875.738  161.213 2097.851
```

```
```

**Comment by nhejazi** [comment]
__Update:__ as of acd061c, the option `glm.family` (intended to make certain computations faster by using `family = stats::gaussian()` instead of `family = stats::binomial()` where possible) has been removed such that it is now only passed to the function `estimateCensoring` and `estimateHazards`. These two functions are called throughout the code base as follows

* `estimateCensoring` - called in both `tmle_mean` and `tmle_hazards`
* `estimateHazards` - called only in `tmle_hazards`

**Comment by nhejazi** [comment]
Benchmarks (fixes to `fast_glm` as of 330feaf):

__n = 1000:__
```
system.time(
    fit <- survtmle(ftime = ftime, ftype = ftype, trt = trt, adjustVars = adjustVars,
                    glm.trt = "1", glm.ftime = glm.ftime, glm.ctime = glm.ctime,
                    method = "hazard", t0 = t_0)
)
'speedglm' ran into an error in estimateTreatment ... using 'glm' instead.
   user  system elapsed 
314.564 196.807 988.427
```
Remark: this runs in finite (tolerable) time, which is a marked improvement over `glm` already. I killed that version before it even ran to completion...

---

Example used for benchmarking:
```
# functions for this simulation
get.ftimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype>0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}

get.ctimeForm <- function(trt, site){
	form <- "-1"
	for(i in unique(trt)){
		for(s in unique(site)){
			form <- c(form, 
			  paste0("I(trt==",i,"& site == ",s," & t==",
			         unique(ftime[ftype==0 & trt==i & site == s]),")",
			         collapse="+"))
		}
	}
	return(paste(form,collapse="+"))
}

# simulate data
n <- 1000
trt <- rbinom(n, 1, 0.5)

# e.g., study site
adjustVars <- data.frame(site = (rbinom(n,1,0.5) + 1))
ftime <- round(1 + runif(n, 1, 350) - trt + adjustVars$site)
ftype <- round(runif(n, 0, 1))

glm.ftime <- get.ftimeForm(trt = trt, site = adjustVars$site)
glm.ctime <- get.ctimeForm(trt = trt, site = adjustVars$site)
```

**Comment by nhejazi** [comment]
3309d0b resolves the error in `estimateTreatment`. `speedglm::speedglm` is used instead of `stats::glm` in all standard use-cases, with `stats::glm` as a fallback. This PR is ready to be merged. @benkeser - feel free to merge when you've had a chance to review the new functionality in `fast_glm`.

**Comment by nhejazi** [comment]
As of e0b2957 `speedglm::speedglm` is only invoked with the `sparse = TRUE` option when fitting a non-intercept model (i.e., when the specified formula is _not_ of the form `. ~ 1`). This is more robust than simply catching calls from `estimateTreatment` as was used in prior fixes.

**Review by benkeser — APPROVED** [review]

**Pull request merged**
